// Noms utilisés pour les pseudos
export const nouns = [
	'Charles de Gaulle',
    'Louis Pasteur',
    'Abbé Pierre',
    'Marie Curie',
    'Coluche',
    'Victor Hugo',
    'Bourvil',
    'Molière',
    'Édith Piaf',
    'Marcel Pagnol',
    'Georges Brassens',
    'Fernandel',
    'Jean de La Fontaine',
    'Jules Verne',
    'Napoléon Bonaparte',
    'Louis de Funès',
    'Jean Gabin',
    'Daniel Balavoine',
    'Serge Gainsbourg',
    'Charlemagne',
    'Lino Ventura',
    'François Mitterrand',
    'Gustave Eiffel',
    'Émile Zola',
    'Jean Moulin',
    'Charles Aznavour',
    'Yves Montand',
    "Jeanne d'Arc",
    'Maréchal Leclerc',
    'Voltaire',
    'Johnny Hallyday',
    'Antoine de Saint-Exupéry',
    'Claude François',
    'Jules Ferry',
    'Louis Lumière',
    'Jacques Chirac',
    'Charles Trenet',
    'Georges Pompidou',
    'Michel Sardou',
    'Jacques Prévert',
    'Louis XIV',
    'David Douillet',
    'Henri Salvador',
    'Jean-Jacques Goldman',
    'Jean Jaurès',
    'Yannick Noah',
    'Albert Camus',
    'Dalida',
    'Nicolas Hulot',
    'Simone Veil',
    'Alain Delon',
    "Patrick Poivre d'Arvor",
    "Aimé Jacquet",
    'Francis Cabrel',
    'Brigitte Bardot',
    'Guy de Maupassant',
    'Alexandre Dumas',
    'Honoré de Balzac',
    'Paul Verlaine',
    'Jean-Jacques Rousseau',
    'Robespierre',
    'Renaud',
    'Claude Monet',
    'Michel Drucker',
    'Vercingétorix',
    'Raymond Poulidor',
    'Baudelaire',
    'Pierre Corneille',
    'Arthur Rimbaud',
    'Georges Clemenceau',
    'José Bové',
    'Jean Ferrat',
    'Henri Matisse',
    'Lionel Jospin',
    'Jean Cocteau',
    'Emile Durkheim',
    'Luc Besson',
    'Coco Chanel',
    'Zinedine Zidane',
    'Jean-Paul Sartre',
	'Emmanuel Macron',
	'Jean-Luc Mélenchon',
    'Catherine Deneuve',
    'Michel Foucault',
    'Gérard Depardieu',
    'Nicolas Sarkozy',
    'Michel Platini',
    'Manu Chao',
    'David Guetta',
	'Jean-Luc Reichmann',
    'Victorien',
    'Paul',
    'Rémi',
    'Théo',
    'Clément',
	'Lucie',
	'Charline',
	'Théa',
	'Robin',
	'Gianito',
	'Antoine',
	'Aimee',
	'Julien',
	'Oscar',
	'Arsène',
	
]

export const possibleNouns = nouns;
